### ISSUE TITLE
Blank page on android

### ISSUE THREAD

**Issue by Blacktoviche** [tomLadder/react-native-echarts-wrapper#10]
I followed your example first install package and copy index.html to android assests  but nothing appear just a white page 
in android log there is no error 
I'm using :
react-native 0.59.4
react-native-echarts-wrapper 1.2.2

**Comment by tomLadder** [comment]
Thank you for reporting. I could reproduce this issue, gonna have a look at it 👍🏻

**Comment by tomLadder** [comment]
Hey @Blacktoviche 

I could find and fix the problem. You can expect a new release within the next days.

**Comment by tomLadder** [comment]
Just released [v1.3.0](https://www.npmjs.com/package/react-native-echarts-wrapper/v/1.3.0) 🎉. 
This release should solve your problem. 

**Attention**
Webview will be no longer part of the react-native-core. Make sure to install `react-native-webview`. (see README for further information)

**Comment by wuwenyuan111** [comment]
I have same problem.
my packages:
"react-native": "0.59.3",
"react-native-webview": "^5.7.1",
"react-native-echarts-wrapper": "^1.3.0",

**Comment by tomLadder** [comment]
Android or IOS. Should be fixed in v1.3.0

**Comment by wuwenyuan111** [comment]
Android

**Comment by tomLadder** [comment]
Do you still face this issue?

**Comment by wuwenyuan111** [comment]
No, it is ok, thanks.
