### ISSUE TITLE
Dynamic loading issue on iOS

### ISSUE THREAD

**Issue by rudrainnovatives** [tomLadder/react-native-echarts-wrapper#16]
Followed your example for dynamic loading of data in graph. Working on Android but getting blank screen on iOS. If data is not dynamic then working good on both platform. Please check the dynamic loading issue on iOS

I am using:
react-native: 0.59.8
react-native-echarts-wrapper: 1.4.0

**Comment by tomLadder** [comment]
Hey @rudrainnovatives !

Thank you for reporting this bug. 🙏 
I could reproduce the issue and a fix will be release in the upcoming version.

**Comment by rudrainnovatives** [comment]
hey @tomLadder ,

i am working on live project that uses echarts. i have to complete a project. I will be thankful if you could release new version as soon as possible.

**Comment by tomLadder** [comment]
Just released [v1.4.1](https://www.npmjs.com/package/react-native-echarts-wrapper/v/1.4.1) 🎉.
This release should solve the dynamic loading issue on ios.
