### ISSUE TITLE
i use Simple example in my project ,show a blank page on ^1.4.1

### ISSUE THREAD

**Issue by Jinzm** [tomLadder/react-native-echarts-wrapper#20]
i total followed README.md ,but show a blank page. i also saw #10,but not helpful.
![image](https://user-images.githubusercontent.com/21049455/60313374-74c6bd00-9991-11e9-9e3a-5b9731b9ed70.png)

**Comment by abrahamAlonzo** [comment]
You have your index.html in your android assets folder, as in [android installation](https://github.com/tomLadder/react-native-echarts-wrapper#android)?

**Comment by Jinzm** [comment]
![image](https://user-images.githubusercontent.com/21049455/60485217-d27b4200-9cce-11e9-88d8-eace3958bd4a.png)
yea

> You have your index.html in your android assets folder, as in [android installation](https://github.com/tomLadder/react-native-echarts-wrapper#android)?

**Comment by tomLadder** [comment]
Have you recompiled your application (`react-native run-android`) ?

**Comment by Allwithyou999** [comment]
The code in README.md show a blank page for iOS

**Comment by JackClown** [comment]
I catched the same problem on Android.  It worked on IOS. RN 0.57.4.

**Comment by Allwithyou999** [comment]
After I added the height in <ECharts> parent, <View> I could resolve this issue.

**Comment by JackClown** [comment]
I find that jsBuilder.js uses arrow functions somewhere, it not works on chrome v44 and before. #25

**Comment by tomLadder** [comment]
Did you add a height to the parent view as @Allwithyou999 suggested? Also try out [v1.4.2](https://www.npmjs.com/package/react-native-echarts-wrapper/v/1.4.2)
Please let me know if this solves the issue.

Thanks,
Tom
