### ISSUE TITLE
Cannot use Moment for formatter

### ISSUE THREAD

**Issue by soyoung97** [tomLadder/react-native-echarts-wrapper#24]
Hi, first I want to thank you for making a good react native echarts wrapper.
I want to use moment for the formatter, but I have trouble making it work,
because in my opinion, I have to import it to use it,
but I can't import moment to the echarts wrapper.

Is there any way that I can use moment for formatter(including the tooltip formatter)?
I attached my code below.

![image](https://user-images.githubusercontent.com/29880214/61262973-39662400-a7c2-11e9-8d90-8c3129d81940.png)

**Comment by tomLadder** [comment]
Hello @soyoung97 !

You can't access anything from your react-native node_modules because these are not available in the webview. In your case i would add a minified version of `moment` to the index.html. Then there your formatter should work.

Cheers,
Tom

**Comment by cloudychen** [comment]
how to use moment? @tomLadder 
can you use moment for formatter now? @soyoung97

**Comment by soyoung97** [comment]
@cloudychen In the last year's case, I didn't use moment. I instead just used `Date`. I don't know if it supports moment now.

**Comment by cloudychen** [comment]
@soyoung97 Thank you for your reply, I can't use moment and I just used `Date` too.
