### ISSUE TITLE
not working on android 5.0

### ISSUE THREAD

**Issue by tiechuimeimei** [tomLadder/react-native-echarts-wrapper#26]
On Android 5.0 mobile phone, histogram can't display normally, showing white screen.Normal Histogram Display on Android 8.0 9.0 Mobile Phone.react-native version number 0.56.0,react-native-echarts-wrapper version number 1.4.1

**Comment by tomLadder** [comment]
Hi. Do you use an emulator or a physical device to test the chart?

**Comment by tiechuimeimei** [comment]
I have used mobile phone VIVO and SAMAUNG test the chart

**Comment by tomLadder** [comment]
Unfortunately i don't have an android device with Android 5, so it's very hard for me to investigate into this issue. Maybe i can reproduce the problem with an emulator.

**Comment by tiechuimeimei** [comment]
Thank you .Hope you can reproduce this problem and solve it. If you have any progress, please let me know.I also continued to try to solve it.

**Comment by tomLadder** [comment]
@tiechuimeimei  Any news on this issue?

**Comment by tiechuimeimei** [comment]
Finally, I only used the 'native-echarts' library.Charts can be displayed properly.
