### ISSUE TITLE
Got rejected from Apple review

### ISSUE THREAD

**Issue by shieer** [tomLadder/react-native-echarts-wrapper#31]
`ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.`

Do we support WKWebview soon?

**Comment by shieer** [comment]
I see the library is using "react-native-webview": "^5.7.0", can we update that?

**Comment by tomLadder** [comment]
We can update it. But in the next version `react-native-webview` will be a peer-dep

**Comment by tomLadder** [comment]
Small info: I will drop the legacy Webview Support in `v2.0.0`. `react-native-webview` (7.x) removed UIWebView...

**Comment by Allwithyou999** [comment]
When will v2.0.0 be published? @tomLadder

**Comment by tomLadder** [comment]
Just released [v2.0.0](https://www.npmjs.com/package/react-native-echarts-wrapper/v/2.0.0) 🎉
