### ISSUE TITLE
RN 0.60

### ISSUE THREAD

**Issue by fynmm** [tomLadder/react-native-echarts-wrapper#32]
RN: 0.60.0
when I npm install `react-native-echarts-wrapper`,
 and install success : 
`+ react-native-echarts-wrapper@1.4.5`
But the warning is  
`react-native-webview@5.12.1 requires a peer of react-native@>=0.57 <0.60 but none is installed. You must install peer dependencies yourself.`
But I use the version 0.60.0 of RN ,So what can I do to solve the problem?

**Comment by lokiiart** [comment]
It's < not <=.

**Comment by tomLadder** [comment]
Just released [v2.0.0](https://www.npmjs.com/package/react-native-echarts-wrapper/v/2.0.0) 🎉

**Comment by fynmm** [comment]
> Just released [v2.0.0](https://www.npmjs.com/package/react-native-echarts-wrapper/v/2.0.0) 🎉

OK,3q
