### ISSUE TITLE
Tried to register two views with the same name RNCWebView? 

### ISSUE THREAD

**Issue by developerashish01** [tomLadder/react-native-echarts-wrapper#35]
any help would be appreciated?

**Comment by tomLadder** [comment]
Yes it's probably in an issue with the dependencies.  I will have a look at it.

**Comment by masiamj** [comment]
@tomLadder Any updates on this? Thanks for you continued great work!

**Comment by tomLadder** [comment]
I'm finished with almost all tests in v2.0.0. Hopefully i can release it this weekend.

Tom

**Comment by tomLadder** [comment]
Just released [v2.0.0](https://www.npmjs.com/package/react-native-echarts-wrapper/v/2.0.0) 🎉
