### ISSUE TITLE
Can't use ECharts with RN 0.60.5

### ISSUE THREAD

**Issue by PinelliaTime** [tomLadder/react-native-echarts-wrapper#36]
create project with react-native-init;
"react-native-webview": "^7.4.0",
"react-native": "0.60.5",
"react-native-webview": "^7.4.0",

The error message is:
`
      Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ECharts`.

This error is located at:
    in RCTView (at View.js:35)
    in View (at src/index.js:182)
    in ECharts (at info.js:65)
    in RCTView (at View.js:35)
    in View (at info.js:64)
    in Info (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:909)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:106)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:71)
    in Screen (at StackViewCard.tsx:93)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:984)
    in RCTView (at View.js:35)
    in View (at screens.native.js:101)
    in ScreenContainer (at StackViewLayout.tsx:393)
    in RCTView (at View.js:35)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:383)
    in PanGestureHandler (at StackViewLayout.tsx:376)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:104)
    in RCTView (at View.js:35)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:41)
    in StackView (at createNavigator.js:80)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:430)
    in NavigationContainer (at App.js:21)
    in App (at renderApplication.js:40)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:35)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:39)
`

hope you can tell me how to resolve this problem,thank you very much.

**Comment by tomLadder** [comment]
did you import it correctly?

```
import { ECharts } from "react-native-echarts-wrapper";
```

**Comment by tomLadder** [comment]
Just released [v2.0.0](https://www.npmjs.com/package/react-native-echarts-wrapper/v/2.0.0) 🎉

**Comment by PinelliaTime** [comment]
thank you very much! when i upgrade to v2.0.0,it works!
