### ISSUE TITLE
blank page only on android 4.x

### ISSUE THREAD

**Issue by ThienBao96** [tomLadder/react-native-echarts-wrapper#45]
I followed your example and succeeded to show chart on almost android devices. Only with android 4.x, nothing showed up.
i am using:
 - "react-native-echarts-wrapper": "2.0.0"
 - "react-native-webview": "5.8.1"
 - "react-native": "0.58.5"

**Comment by tomLadder** [comment]
Hey @ThienBao96 

Do you have dome further information/specs about the device?

**Comment by Arbaaz1** [comment]
Hi I am getting blank white screeen on my react native app
version e-chart-2.0.0
react native version-0.71
