### ISSUE TITLE
work fine in expo but not working in react native Android

### ISSUE THREAD

**Issue by kishanp2585** [tomLadder/react-native-echarts-wrapper#50]
"react": "16.9.0",
"react-native": "0.61.5",
"react-native-echarts-wrapper": "^2.0.0",
"react-native-webview": "^8.0.6",

![Screenshot_1580990280](https://user-images.githubusercontent.com/44631768/73935339-51d89000-4906-11ea-868c-0bf4b6aced49.png)

**Comment by tomLadder** [comment]
@kishanp2585 Can you give me any further information? code to reproduce the problem?
