### ISSUE TITLE
Set default renderer to svg or use props

### ISSUE THREAD

**Issue by Zeral-Zhang** [tomLadder/react-native-echarts-wrapper#51]
Set default renderer to svg or use props, the SVG renderer has provided a better FPS performance in mobile devices.
link：[Render by Canvas or SVG](https://echarts.apache.org/en/tutorial.html#Render%20by%20Canvas%20or%20SVG)

**Comment by tomLadder** [comment]
@Zeral-Zhang Yes you are totally right. It was already possible to the the render to "svg" through props. But i found out that touch events/gestures are not handled proberly when rendering with svg. But for static charts it makes sense. Will add it again in the upcomming release.
