### ISSUE TITLE
How to pass custom parameter to tooltip 

### ISSUE THREAD

**Issue by prancky** [tomLadder/react-native-echarts-wrapper#9]
Hi all,
I want to know how to pass extra parameter to tooltip.
<img width="362" alt="Screen Shot 2019-03-15 at 11 26 11 AM" src="https://user-images.githubusercontent.com/18732057/54413334-4ba05a80-471b-11e9-8174-4293013fd9c9.png">

**Comment by tomLadder** [comment]
This is not a issue with this library. You should check the [ECharts documentation](https://echarts.apache.org/option.html#tooltip.formatter)
